### ISSUE TITLE
UNraid Docker?

### ISSUE THREAD

**Issue by mbc0** [ftpgrab/docker#2]
Hi,

Not really an issue but would love to buy you a few beers if you could make an unRAID docker of ftpgrab ;-) would save me having to run an Ubuntu VM :-D

**Comment by crazy-max** [comment]
Hi @mbc0,

I'm not familiar with unRAID but from what I see you can already use the FTPGrab Docker image with the [GUI of unRAID](https://lime-technology.com/forums/topic/36057-noobie-docker-setup-guide/?tab=comments#comment-345882). Maybe you want me to set up a template for unRAID?

**Comment by mbc0** [comment]
Hi mate, yes that would be amazing! as I said if I could use a docker version I would not need to run a VM! :-) I have tried to make a template and get it working in unRAID but I am not clever enough :-D so defo worth a few beers ;-)

**Comment by crazy-max** [comment]
Hi @mbc0,

It has been a long time :innocent: As you may know, FTPGrab has been completely revised since 5.0.0 and can be used across many platforms and architectures.

Maybe you can use [one of the binaries available](https://ftpgrab.github.io/doc/get-started/#binary) on your platform now ?

Keep me in touch!
